[package]
name = "lilos-watch"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
lilos.workspace = true

[lib]
test = false
bench = false
