[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "qemu-system-arm -cpu cortex-m3 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -s -kernel"

rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Ltestsuite/lm3s6965",
]

[build]
target = "thumbv7m-none-eabi"
