[package]
name = "lilos-semaphore"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
lilos = {version = "1.0.0", path = "../os", default-features = false}
pin-project-lite = "0.2.14"

[lib]
test = false
bench = false
